notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
python:
- 3.6
- 3.7
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: skoef
  password:
    secure: ANp4vrfn/SIxc5vDUaxqnIE8mdfZloLcf2Hvc+8xdnIbKFrRO9i9m2LqIlBSoqfbvuRy5HcH0m7lup6BlU31Y37dcsbzjdjW8C9lAWzYETH73ZMPMnhlkkdeP4QsxcAgpvffvdg9cMPE8WxOO6wf+6oNq0Lu2kK+PiZ5QeLbuIHP0xz8Itk7CZe2on9mJxp4axMXihBaHWgRdNFY5ajxF6hESrp7qSs5FOhZFgwB1a04OME68TsiS0LirfDC0sPOr/stj9/o2aajUwgx/dytw0iDaN/MIMBvcxLbu+mXTJ2oh8L7p+LM0precwqIhSbuKjveMgPUUmst8yOqbJwBpdZo+C1zxlG6YPfKP+K1CQu8dzCUWoEWtlk2qPmijS/MPsiC6yzE6RUxLHepkpn4ppfh8e9HUHMJA011v8jN9VHlp4k57s4sEqKiIfkFIEktGs+sAZO4BAjC/nDSckHUpTbcWDrS1AAnsuJnFcTQCTGA8EV2S8GcSvNquNl54yZGcplvkn+MAHEtUBxmnsshSU2gmhLUxiT9w9giEih/0FS9aruyl9K7aWCw3H+tYBrHNh+n/MZ95BGo3BytEY6qSnQlrhoRSGxy0slLUa2nYP6kLItFsRpewrqz37Fhcf/FiweFVe2O2JGAfSPkiAWWpeMT3n+deOVKO+tjr7m+WAE=
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
